# Generated by Django 5.1.6 on 2025-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('age', models.IntegerField()),
                ('is_fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
